<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ueberland"
 *
 * Auto generated by Extension Builder 2018-08-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'ueberland',
    'description' => 'Management System for Überland Tecklenburg',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-10.4.99',
			'vhs' => '*'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
